### DISCUSSION TITLE
Brainstorming on persisting the requests

### DISCUSSION THREAD

**Discussion by kannananil** [req-io/req.io#38] [Ideas]
This is a discussion thread to brainstorm on the initial ideas on persisting the requests and related data of **req.io** so that users would be able to come back and utilise the same requests even after closing the application. (This is different from the short time runtime state management that could be done via redux or similar frameworks which is yet to be implemented)

Instead of over complicating things by involving our usual concepts like collections, environments etc which we used to follow in all the main http clients we have seen. These extended concepts like collections, folders, nested folders, environments etc can be brought going forward in future. 

We will start of with a simple scratchpad this acts as a collection of all the requests a user holds. This data for the scratchpad will be stored within the users machines storage as normal file structure  with each file mapped to each request.  The path for this scratch pad will be by default configured in an env variable for the application to utilise something like `$HOME/.reqio/scratchpad` which can be made configurable for users through our application UI itself or via updating the env variable.

Our intent is to make this request file simpler in structure, easily accessible and understandable. We could potentially follow any standard and simpler structures which follows json or yaml approach(or could come up with our own structure too if necessary)

@keerthanak-tw and @Pravithaop  share your thoughts

**Comment by kannananil** [comment]
Attaching two example structure of the request file structure to demonstrate the idea clearly

**POST request**

```
name: Add an expense
type: request
method: POST
url: http://expensetracker.io/expense
body:
  {
    "title": "Train ticket",
    "category": "tavel",
    "amount": 456.30
    "date": "24/10/2023"
  }
headers:
  - key: Content-Type
    value: application/json
  - key: x-api-key
    value: abcdefg
```

**GET request** 
```
name: Get travel expenses
type: request
method: GET
url: http://expensetracker.io/expense
headers:
  - key: Content-Type
    value: application/json
  - key: x-api-key
    value: abcdefg
query:
  - key: category
    value: travel
```
